// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8BJ8vAN6bRejaSv_l_eFgOflFH7RQFoc',
    appId: '1:952893296966:web:3a9ee5d8d5ddb60f351547',
    messagingSenderId: '952893296966',
    projectId: 'fir-ecom-6fe01',
    authDomain: 'fir-ecom-6fe01.firebaseapp.com',
    storageBucket: 'fir-ecom-6fe01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTS3p0AcYOQH9zmQCgI_RAhbVrnyXyUo',
    appId: '1:952893296966:android:d16bd19d46051c61351547',
    messagingSenderId: '952893296966',
    projectId: 'fir-ecom-6fe01',
    storageBucket: 'fir-ecom-6fe01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPXX_hGKSvpP99692tONedWMq_3dPEbRo',
    appId: '1:952893296966:ios:4987b4f2ae8c523b351547',
    messagingSenderId: '952893296966',
    projectId: 'fir-ecom-6fe01',
    storageBucket: 'fir-ecom-6fe01.appspot.com',
    iosBundleId: 'com.example.practiceEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPXX_hGKSvpP99692tONedWMq_3dPEbRo',
    appId: '1:952893296966:ios:8e67ca2405e368f4351547',
    messagingSenderId: '952893296966',
    projectId: 'fir-ecom-6fe01',
    storageBucket: 'fir-ecom-6fe01.appspot.com',
    iosBundleId: 'com.example.practiceEcom.RunnerTests',
  );
}
